Repository rster2002/Project-Periode-4, pull requests merged in 2020-05, with the labels that each got.

#8 Niek
  DAL/CustomerDAO.cs
  DAL/DAL.csproj
  DAL/TableDAO.cs
  Logic/CustomerService.cs
  Logic/Logic.csproj
  Logic/TableService.cs
  UI/App.config
Labels: Feature

#7 Finished OrderDAO
  DAL/DAL.csproj
  DAL/OrderDAO.cs
  Test Console/App.config
  Test Console/Program.cs
Labels: Feature

#10 ReceiptDAO & RegisterDAO afgemaakt
  DAL/ReceiptDAO.cs
Labels: Feature

#3 Renaming to PascalCase
  .editorconfig
  DAL/CustomerDAO.cs
  DAL/MenuDAO.cs
  DAL/MenuItemDAO.cs
  DAL/OrderDAO.cs
  DAL/ReceiptDAO.cs
  DAL/RegisterDAO.cs
  DAL/ReservationDAO.cs
  DAL/SQLInterface.cs
  DAL/TableDAO.cs
  Logic/CustomerService.cs
  Logic/MenuItemService.cs
  Logic/MenuService.cs
  Logic/TableService.cs
  Model/Customer.cs
  Model/Menu.cs
  Model/MenuItem.cs
  Model/Order.cs
  Model/Receipt.cs
  Model/Register.cs
  Model/Reservation.cs
  Model/Staff.cs
  Model/Table.cs
  Test Console/Program.cs
Labels: Enhancement, Proposal

#12 Split 'Execute' method into multiple methods
  DAL/ReservationDAO.cs
  DAL/SQLInterface.cs
Labels: Enhancement

#16 Finished Reservation and Order Service
  DAL/OrderDAO.cs
  DAL/ReservationDAO.cs
  Logic/Logic.csproj
  Logic/OrderService.cs
  Logic/ReservationService.cs
  Model/MenuItem.cs
  Model/Order.cs
  Test Console/Program.cs
Labels: Feature

#18 Ryan
  DAL/MenuDAO.cs
  DAL/MenuItemDAO.cs
  Test Console/Program.cs
Labels: Feature
